// ============================================================================
// ui/tui/types.cpp — Menu structure definition
// ============================================================================

#include "types.hpp"

namespace elmos::ui::tui {

auto build_menu_structure() -> std::vector<MenuItem> {
    return {
        {.label = "Workspace",
         .desc = "Initialize and manage workspace",
         .children =
             {
                 {.label = "Initialize",
                  .desc = "Create image & mount",
                  .action = "init:workspace",
                  .command = "elmos init",
                  .args = {"init"}},
                 {.label = "Status",
                  .desc = "Show workspace status",
                  .action = "workspace:status",
                  .command = "elmos status",
                  .args = {"status"}},
                 {.label = "Exit",
                  .desc = "Unmount & cleanup",
                  .action = "workspace:exit",
                  .command = "elmos exit",
                  .args = {"exit"}},
             }},
        {.label = "Arch",
         .desc = "Set target architecture",
         .children =
             {
                 {.label = "Show",
                  .desc = "Show current config",
                  .action = "arch:show",
                  .command = "elmos arch show",
                  .args = {"arch", "show"}},
                 {.label = "Set",
                  .desc = "Set architecture",
                  .action = "arch:set",
                  .command = "elmos arch <target>",
                  .needs_input = true,
                  .input_prompt = "Architecture (arm64/arm/riscv):",
                  .input_placeholder = "arm64"},
             }},
        {.label = "Kernel",
         .desc = "Configure and build Linux kernel",
         .children =
             {
                 {.label = "Status",
                  .desc = "Show kernel status",
                  .action = "kernel:status",
                  .command = "elmos kernel status",
                  .args = {"kernel", "status"}},
                 {.label = "Clone",
                  .desc = "Download source",
                  .action = "kernel:clone",
                  .command = "elmos kernel clone",
                  .args = {"kernel", "clone"}},
                 {.label = "Pull",
                  .desc = "Update source",
                  .action = "kernel:pull",
                  .command = "elmos kernel pull",
                  .args = {"kernel", "pull"}},
                 {.label = "Switch",
                  .desc = "Checkout ref",
                  .action = "kernel:switch",
                  .command = "elmos kernel switch <ref>",
                  .needs_input = true,
                  .input_prompt = "Branch/Tag (? for list):",
                  .input_placeholder = "v6.7"},
                 {.label = "Reset",
                  .desc = "Reclone source",
                  .action = "kernel:reset",
                  .command = "elmos kernel reset",
                  .args = {"kernel", "reset"}},
                 {.label = "Config",
                  .desc = "Configure kernel",
                  .action = "kernel:config",
                  .command = "elmos kernel config <type>",
                  .needs_input = true,
                  .input_prompt = "Config (defconfig/tinyconfig/menuconfig):",
                  .input_placeholder = "defconfig"},
                 {.label = "Build",
                  .desc = "Compile kernel",
                  .action = "kernel:build",
                  .command = "elmos kernel build",
                  .args = {"kernel", "build"}},
                 {.label = "Install",
                  .desc = "Link build artifacts",
                  .action = "kernel:install",
                  .command = "elmos kernel install",
                  .args = {"kernel", "install"}},
                 {.label = "Clean",
                  .desc = "Remove artifacts",
                  .action = "kernel:clean",
                  .command = "elmos kernel clean",
                  .args = {"kernel", "clean"}},
             }},
        {.label = "Modules",
         .desc = "Manage kernel modules",
         .children =
             {
                 {.label = "List",
                  .desc = "Show modules",
                  .action = "module:list",
                  .command = "elmos module list",
                  .args = {"module", "list"}},
                 {.label = "Build",
                  .desc = "Build module(s)",
                  .action = "module:build",
                  .command = "elmos module build [name]",
                  .needs_input = true,
                  .input_prompt = "Module (blank=all):",
                  .input_placeholder = ""},
                 {.label = "New",
                  .desc = "Create module",
                  .action = "module:new",
                  .command = "elmos module new <name>",
                  .needs_input = true,
                  .input_prompt = "Module name:",
                  .input_placeholder = "hello_world"},
                 {.label = "Clean",
                  .desc = "Remove binaries",
                  .action = "module:clean",
                  .command = "elmos module clean",
                  .args = {"module", "clean"}},
             }},
        {.label = "Apps",
         .desc = "Manage userspace apps",
         .children =
             {
                 {.label = "List",
                  .desc = "Show apps",
                  .action = "app:list",
                  .command = "elmos app list",
                  .args = {"app", "list"}},
                 {.label = "Build",
                  .desc = "Build app(s)",
                  .action = "app:build",
                  .command = "elmos app build [name]",
                  .needs_input = true,
                  .input_prompt = "App (blank=all):",
                  .input_placeholder = ""},
                 {.label = "New",
                  .desc = "Create app",
                  .action = "app:new",
                  .command = "elmos app new <name>",
                  .needs_input = true,
                  .input_prompt = "App name:",
                  .input_placeholder = "hello_app"},
                 {.label = "Clean",
                  .desc = "Remove binaries",
                  .action = "app:clean",
                  .command = "elmos app clean",
                  .args = {"app", "clean"}},
             }},
        {.label = "QEMU",
         .desc = "Run kernel in emulator",
         .children =
             {
                 {.label = "Run",
                  .desc = "Boot kernel",
                  .action = "qemu:run",
                  .command = "elmos qemu run",
                  .interactive = true,
                  .args = {"qemu", "run"}},
                 {.label = "Debug",
                  .desc = "With GDB server",
                  .action = "qemu:debug",
                  .command = "elmos qemu debug",
                  .interactive = true,
                  .args = {"qemu", "debug"}},
             }},
        {.label = "GDB",
         .desc = "Connect debugger",
         .action = "gdb:connect",
         .command = "elmos gdb",
         .args = {"gdb"}},
        {.label = "RootFS",
         .desc = "Manage root filesystem",
         .children =
             {
                 {.label = "Status",
                  .desc = "Show rootfs status",
                  .action = "rootfs:status",
                  .command = "elmos rootfs status",
                  .args = {"rootfs", "status"}},
                 {.label = "Build",
                  .desc = "Build rootfs",
                  .action = "rootfs:build",
                  .command = "elmos rootfs build -s <size>",
                  .needs_input = true,
                  .input_prompt = "Size (e.g. 5G):",
                  .input_placeholder = "5G"},
                 {.label = "Clean",
                  .desc = "Remove rootfs",
                  .action = "rootfs:clean",
                  .command = "elmos rootfs clean",
                  .args = {"rootfs", "clean"}},
             }},
        {.label = "Bootloader",
         .desc = "Build and install U-Boot",
         .children =
             {
                 {.label = "Build",
                  .desc = "Build bootloader",
                  .action = "bootloader:build",
                  .command = "elmos bootloader build",
                  .args = {"bootloader", "build"}},
                 {.label = "Install",
                  .desc = "Link bootloader artifacts",
                  .action = "bootloader:install",
                  .command = "elmos bootloader install",
                  .args = {"bootloader", "install"}},
                 {.label = "Blobs",
                  .desc = "List/download firmware blobs",
                  .action = "bootloader:blobs",
                  .command = "elmos bootloader blobs",
                  .args = {"bootloader", "blobs"}},
             }},
        {.label = "Doctor",
         .desc = "Check environment",
         .action = "doctor:check",
         .command = "elmos doctor",
         .args = {"doctor"}},
        {.label = "Toolchains",
         .desc = "Manage cross-compiler toolchains",
         .children =
             {
                 {.label = "Status",
                  .desc = "Show installed toolchains",
                  .action = "toolchain:status",
                  .command = "elmos toolchains status",
                  .args = {"toolchains", "status"}},
                 {.label = "Clone",
                  .desc = "Install crosstool-ng",
                  .action = "toolchain:clone",
                  .command = "elmos toolchains clone",
                  .args = {"toolchains", "clone"}},
                 {.label = "List",
                  .desc = "List available targets",
                  .action = "toolchain:list",
                  .command = "elmos toolchains list",
                  .args = {"toolchains", "list"}},
                 {.label = "Select",
                  .desc = "Select toolchain target",
                  .action = "toolchain:select",
                  .command = "elmos toolchains <target>",
                  .needs_input = true,
                  .input_prompt = "Target (e.g. riscv64-unknown-linux-gnu):",
                  .input_placeholder = "riscv64-unknown-linux-gnu"},
                 {.label = "Build",
                  .desc = "Build selected toolchain",
                  .action = "toolchain:build",
                  .command = "elmos toolchains build",
                  .args = {"toolchains", "build"}},
                 {.label = "Install",
                  .desc = "Link selected toolchain",
                  .action = "toolchain:install",
                  .command = "elmos toolchains install",
                  .args = {"toolchains", "install"}},
                 {.label = "Env",
                  .desc = "Show env variables",
                  .action = "toolchain:env",
                  .command = "elmos toolchains env",
                  .args = {"toolchains", "env"}},
                 {.label = "Menuconfig",
                  .desc = "Configure toolchain",
                  .action = "toolchain:menuconfig",
                  .command = "elmos toolchains menuconfig",
                  .interactive = true,
                  .args = {"toolchains", "menuconfig"}},
                 {.label = "Clean",
                  .desc = "Clean toolchain build",
                  .action = "toolchain:clean",
                  .command = "elmos toolchains clean",
                  .args = {"toolchains", "clean"}},
             }},
    };
}

}  // namespace elmos::ui::tui
